# Generated by Django 5.1 on 2024-08-23 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='circle_images/', verbose_name='Изображение')),
                ('title1', models.CharField(max_length=255, verbose_name='Дополнительное название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('description1', models.TextField(verbose_name='Дополнительное описание')),
                ('video_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео')),
                ('text1', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст')),
                ('description2', models.TextField(blank=True, null=True, verbose_name='Дополнительное описание')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Кружки',
                'verbose_name_plural': 'Кружки',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('name', models.CharField(max_length=255, verbose_name='Название зала')),
                ('dimensions', models.CharField(max_length=255, verbose_name='Размеры зала')),
                ('capacity', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('covering', models.CharField(max_length=100, verbose_name='Покрытие')),
                ('inventory', models.TextField(verbose_name='Инвентарь')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата за час')),
                ('title1', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveIntegerField(verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('07:00', '07:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], max_length=5, verbose_name='Время')),
                ('day', models.CharField(choices=[('Mon', 'Пн'), ('Tue', 'Вт'), ('Wed', 'Ср'), ('Thu', 'Чт'), ('Fri', 'Пт'), ('Sat', 'Сб')], max_length=3, verbose_name='День')),
                ('sport', models.CharField(max_length=255, verbose_name='Спорт')),
                ('age_group', models.CharField(max_length=255, verbose_name='Возрастная группа')),
                ('coach', models.CharField(max_length=255, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Расписание тренировки',
                'verbose_name_plural': 'Расписания тренировок',
            },
        ),
        migrations.CreateModel(
            name='CircleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='circle_images/', verbose_name='Изображение')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='football.circle', verbose_name='Кружок')),
            ],
            options={
                'verbose_name': 'Изображение кружка',
                'verbose_name_plural': 'Изображения кружков',
            },
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hall_images/', verbose_name='Изображение')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='football.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Изображение зала',
                'verbose_name_plural': 'Изображения залов',
            },
        ),
    ]
