# Generated by Django 5.0.6 on 2024-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Tennis', 'Tennis'), ('Swimming', 'Swimming'), ('Volleyball', 'Volleyball'), ('Taekwondo', 'Taekwondo'), ('Boxing', 'Boxing'), ('Cycling', 'Cycling'), ('Yoga', 'Yoga')], max_length=50)),
                ('class_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
