# Generated by Django 5.1.1 on 2024-09-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gyminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sport_classes/'),
        ),
    ]
