# Generated by Django 5.1.1 on 2024-09-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sportclass_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyminfo',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
