# Generated by Django 4.2.11 on 2024-08-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('description', models.TextField()),
                ('training_zones', models.CharField(max_length=255)),
                ('pool', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('schedule_day', models.CharField(max_length=50)),
                ('working_hours', models.CharField(max_length=50)),
                ('installment_period', models.CharField(choices=[('6', '6 months'), ('9', '9 months'), ('12', '12 months')], max_length=10)),
                ('website_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website_link', models.URLField(blank=True, max_length=255, null=True)),
                ('tariffs', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(default='Unknown', max_length=255)),
                ('card_number', models.CharField(default='0000000000000000', max_length=16)),
                ('expiry_date', models.CharField(default='00/00', max_length=5)),
                ('cvc', models.CharField(default='000', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Savephoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
            ],
        ),
    ]
