# Generated by Django 5.0.6 on 2024-08-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_savephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='duration',
            field=models.IntegerField(db_default=7),
        ),
    ]
