# Generated by Django 5.0.6 on 2024-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_advertisement_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(default='default_charge_id', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(default='No description', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
