# Generated by Django 5.0.6 on 2024-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_remove_payment_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvc',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(default='00/00', max_length=5),
        ),
    ]
