# Generated by Django 5.0.6 on 2024-08-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_payment_card_holder_name_payment_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
