# Generated by Django 5.0.6 on 2024-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_remove_payment_amount_remove_payment_charge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.CharField(default='0000', max_length=3),
        ),
    ]
