# Generated by Django 5.0.6 on 2024-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_alter_payment_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
