# Generated by Django 5.1 on 2024-08-27 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('sport', models.CharField(choices=[('basketball', 'Баскетбол'), ('football', 'Футбол'), ('volleyball', 'Волейбол'), ('tennis', 'Тенис'), ('boxing', 'Бокс'), ('cycling', 'Велоспорт'), ('taekwondo', 'Таэквондо'), ('swimming', 'Плавание'), ('yoga', 'Йога')], max_length=20, verbose_name='Спорт')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('sport', models.CharField(choices=[('basketball', 'Баскетбол'), ('football', 'Футбол'), ('volleyball', 'Волейбол'), ('tennis', 'Тенис'), ('boxing', 'Бокс'), ('cycling', 'Велоспорт'), ('taekwondo', 'Таэквондо'), ('swimming', 'Плавание'), ('yoga', 'Йога')], max_length=20, verbose_name='Спорт')),
                ('payment', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], max_length=20, verbose_name='Оплата')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='user_admin.trainer')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
