# Generated by Django 5.1.1 on 2024-10-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='advertisements/')),
                ('title', models.CharField(max_length=255)),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('site_link', models.URLField()),
                ('installment_plan', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'реклама',
                'verbose_name_plural': 'реклама',
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='circle_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='circle_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='circle_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='circle_images/')),
                ('sports', models.CharField(choices=[('Баскетбол', 'Баскетбол'), ('Футбол', 'Футбол'), ('Волейбол', 'Волейбол'), ('Тенис', 'Тенис'), ('Бокс', 'Бокс'), ('Велоспорт', 'Велоспорт'), ('Таэквондо', 'Таэквондо'), ('Плавание', 'Плавание'), ('Йога', 'Йога')], max_length=20, verbose_name='Виды спорта')),
                ('header1', models.CharField(blank=True, max_length=255, verbose_name='Заголовок 1')),
                ('description1', models.TextField(blank=True, verbose_name='Описание 1')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('header2', models.CharField(blank=True, max_length=255, verbose_name='Заголовок 2')),
                ('description2', models.TextField(blank=True, verbose_name='Описание 2')),
                ('header3', models.CharField(blank=True, max_length=255, verbose_name='Заголовок 3')),
                ('description3', models.TextField(blank=True, verbose_name='Описание 3')),
                ('header4', models.CharField(blank=True, max_length=255, verbose_name='Заголовок 4')),
                ('description4', models.TextField(blank=True, verbose_name='Описание 4')),
            ],
            options={
                'verbose_name': 'Кружок',
                'verbose_name_plural': 'Кружки',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(choices=[('Баскетбол', 'Баскетбол'), ('Футбол', 'Футбол'), ('Волейбол', 'Волейбол'), ('Тенис', 'Тенис'), ('Бокс', 'Бокс'), ('Велоспорт', 'Велоспорт'), ('Таэквондо', 'Таэквондо'), ('Плавание', 'Плавание'), ('Йога', 'Йога')], max_length=20, verbose_name='Виды спорта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Изображение')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Изображение')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Изображение')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('size', models.CharField(max_length=50, verbose_name='Размеры')),
                ('inventory', models.TextField(verbose_name='Инвентарь')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата за час')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('coverage', models.CharField(max_length=100, verbose_name='Покрытие')),
                ('hall_type', models.CharField(max_length=100, verbose_name='Тип')),
                ('shower', models.BooleanField(default=False, verbose_name='Душевая')),
                ('lighting', models.BooleanField(default=False, verbose_name='Освещение')),
                ('dressing_room', models.BooleanField(default=False, verbose_name='Раздевалка')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('sport', models.CharField(max_length=50, verbose_name='Спорт')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за месяц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=12, verbose_name='День недели')),
                ('category', models.CharField(choices=[('adults', 'Взрослые'), ('teens', 'Подростки'), ('kids', 'Дети')], max_length=10, verbose_name='Категория')),
                ('start_time', models.TimeField(verbose_name='Начало занятия')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Окончание занятия')),
                ('category1', models.CharField(choices=[('adults', 'Взрослые'), ('teens', 'Подростки'), ('kids', 'Дети')], max_length=10, verbose_name='Категория')),
                ('day_of_week1', models.CharField(max_length=15, verbose_name='День недели')),
                ('start_time1', models.TimeField(verbose_name='Начало занятия')),
                ('end_time1', models.TimeField(blank=True, null=True, verbose_name='Окончание занятия')),
                ('category2', models.CharField(choices=[('adults', 'Взрослые'), ('teens', 'Подростки'), ('kids', 'Дети')], max_length=10, verbose_name='Категория')),
                ('day_of_week2', models.CharField(max_length=15, verbose_name='День недели')),
                ('start_time2', models.TimeField(verbose_name='Начало занятия')),
                ('end_time2', models.TimeField(blank=True, null=True, verbose_name='Окончание занятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное расписание (True)')),
                ('сircle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='administrator.circle', verbose_name='кружки')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(upload_to='trainers_photos/', verbose_name='Фото')),
                ('sport', models.CharField(choices=[('Баскетбол', 'Баскетбол'), ('Футбол', 'Футбол'), ('Волейбол', 'Волейбол'), ('Тенис', 'Тенис'), ('Бокс', 'Бокс'), ('Велоспорт', 'Велоспорт'), ('Таэквондо', 'Таэквондо'), ('Плавание', 'Плавание'), ('Йога', 'Йога')], max_length=20, verbose_name='Спорт')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'unique_together': {('email', 'sport')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('sport', models.CharField(choices=[('Баскетбол', 'Баскетбол'), ('Футбол', 'Футбол'), ('Волейбол', 'Волейбол'), ('Тенис', 'Тенис'), ('Бокс', 'Бокс'), ('Велоспорт', 'Велоспорт'), ('Таэквондо', 'Таэквондо'), ('Плавание', 'Плавание'), ('Йога', 'Йога')], max_length=20, verbose_name='Спорт')),
                ('payment_method', models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта'), ('Перевод', 'Перевод')], max_length=10, verbose_name='Метод оплаты')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='administrator.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=12, verbose_name='День недели')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное расписание (True)')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='administrator.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'unique_together': {('hall', 'day_of_week', 'opening_time')},
            },
        ),
    ]
