# Generated by Django 5.1.1 on 2024-11-04 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='image',
        ),
        migrations.AlterField(
            model_name='hall',
            name='image1',
            field=models.ImageField(upload_to='hall_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image2',
            field=models.ImageField(upload_to='hall_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image3',
            field=models.ImageField(upload_to='hall_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
