# Generated by Django 5.1.1 on 2024-10-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='file1',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='file2',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='file3',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(upload_to='hall_image/', verbose_name='Изображение'),
        ),
    ]
