# Generated by Django 5.1.1 on 2024-10-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(default=1, upload_to='hall_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='image1',
            field=models.ImageField(default=1, upload_to='hall_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='image2',
            field=models.ImageField(default=1, upload_to='hall_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='image3',
            field=models.ImageField(default=1, upload_to='hall_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
