# Generated by Django 5.1.1 on 2024-09-25 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'Графики работы'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment',
        ),
        migrations.AddField(
            model_name='circleimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], default=1, max_length=10, verbose_name='Метод оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hallimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sport',
            field=models.CharField(choices=[('basketball', 'Баскетбол'), ('football', 'Футбол'), ('volleyball', 'Волейбол'), ('tennis', 'Теннис'), ('boxing', 'Бокс'), ('cycling', 'Велоспорт'), ('taekwondo', 'Таэквондо'), ('swimming', 'Плавание'), ('yoga', 'Йога')], max_length=20, verbose_name='Спорт'),
        ),
        migrations.AlterField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='administrator.trainer', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=10, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='sport',
            field=models.CharField(choices=[('basketball', 'Баскетбол'), ('football', 'Футбол'), ('volleyball', 'Волейбол'), ('tennis', 'Теннис'), ('boxing', 'Бокс'), ('cycling', 'Велоспорт'), ('taekwondo', 'Таэквондо'), ('swimming', 'Плавание'), ('yoga', 'Йога')], max_length=20, verbose_name='Спорт'),
        ),
        migrations.CreateModel(
            name='Schedul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('adults', 'Взрослые'), ('teens', 'Подростки'), ('kids', 'Дети')], max_length=10, verbose_name='Возрастная группа')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=10, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало занятий')),
                ('end_time', models.TimeField(verbose_name='Конец занятий')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='administrator.circle', verbose_name='Кружок')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
