# Generated by Django 5.1.1 on 2024-10-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title3',
            field=models.CharField(max_length=255),
        ),
    ]
