# Generated by Django 5.1.1 on 2024-10-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_delete_hallimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Изображение'),
        ),
    ]
