# Generated by Django 5.1.1 on 2024-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_hall_image_alter_hall_image1_alter_hall_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='photo',
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainers_photos/'),
        ),
    ]
