# Generated by Django 5.1.1 on 2024-10-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_advertisement_file1_advertisement_file2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='image2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='image3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
