# Generated by Django 5.1.1 on 2024-10-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_hall_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='circle_images/'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='circle_images/'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='circle_images/'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='circle_images/'),
        ),
        migrations.DeleteModel(
            name='CircleImage',
        ),
    ]
