# Generated by Django 5.1.1 on 2024-10-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_hall_image1_hall_image2_hall_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='image1',
            field=models.ImageField(default=1, upload_to='circle_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='image2',
            field=models.ImageField(default=1, upload_to='circle_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='image3',
            field=models.ImageField(default=1, upload_to='circle_images/'),
            preserve_default=False,
        ),
    ]
