# Generated by Django 5.1.1 on 2024-10-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_advertisement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта'), ('Перевод', 'Перевод')], max_length=10, verbose_name='Метод оплаты'),
        ),
    ]
