# Generated by Django 5.1.1 on 2024-11-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_hall_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/'),
        ),
    ]
