# Generated by Django 5.1.1 on 2024-10-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_circle_image_alter_circle_image1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='administrator.hall', verbose_name='Зал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/', verbose_name='Изображение'),
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('hall', 'day_of_week', 'opening_time')},
        ),
    ]
