# Generated by Django 5.1.1 on 2024-10-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_circle_image1_circle_image2_circle_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='file3',
        ),
    ]
