# Generated by Django 5.1.1 on 2024-10-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_client_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
