# Generated by Django 5.1.1 on 2024-10-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_workschedule_unique_together_workschedule_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedul',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активное расписание (True)'),
        ),
        migrations.AddField(
            model_name='schedul',
            name='сircle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='administrator.circle', verbose_name='кружки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedul',
            name='day_of_week',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=12, verbose_name='День недели'),
        ),
    ]
