# Generated by Django 5.1.1 on 2024-09-25 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='hallarena',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sport.hallarena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='hallinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sport.hallinfo'),
            preserve_default=False,
        ),
    ]
