# Generated by Django 5.1.1 on 2024-09-25 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_hall_hallarena_hall_hallinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='hallarena',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='hallinfo',
        ),
        migrations.AddField(
            model_name='hallarena',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='sport.hall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hallinfo',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='sport.hall'),
            preserve_default=False,
        ),
    ]
