# Generated by Django 5.1.1 on 2024-10-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0002_userprofile_email_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
