# Generated by Django 5.1.1 on 2024-11-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
