# Generated by Django 5.1.1 on 2024-10-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0002_rename_age_group_payment1_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment1',
            old_name='age',
            new_name='category',
        ),
    ]
