# Generated by Django 5.1.1 on 2024-10-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0003_rename_age_payment1_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment1',
            name='category',
        ),
    ]
