# Generated by Django 5.1.1 on 2024-10-23 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0005_payment1_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment1',
            name='category',
        ),
        migrations.RemoveField(
            model_name='payment1',
            name='day_of_week',
        ),
        migrations.AlterField(
            model_name='payment1',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активное расписание'),
        ),
        migrations.AlterField(
            model_name='payment1',
            name='sport',
            field=models.CharField(choices=[('баскетбол', 'Баскетбол'), ('футбол', 'Футбол'), ('волейбол', 'Волейбол'), ('теннис', 'Тенис'), ('бокс', 'Бокс'), ('велоспорт', 'Велоспорт'), ('таэквондо', 'Таэквондо'), ('плавание', 'Плавание'), ('йога', 'Йога')], max_length=20, verbose_name='Спорт'),
        ),
        migrations.CreateModel(
            name='Schedul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('понедельник', 'Понедельник'), ('вторник', 'Вторник'), ('среда', 'Среда'), ('четверг', 'Четверг'), ('пятница', 'Пятница'), ('суббота', 'Суббота'), ('воскресенье', 'Воскресенье')], max_length=12, verbose_name='День недели')),
                ('category', models.CharField(choices=[('взрослые', 'Взрослые'), ('подростки', 'Подростки'), ('дети', 'Дети')], max_length=10, verbose_name='Категория')),
                ('start_time', models.TimeField(verbose_name='Начало занятия')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Окончание занятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное расписание')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Платежи', to='client_account.payment1', verbose_name='')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
