# Generated by Django 5.1.1 on 2024-10-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0006_remove_payment1_category_remove_payment1_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment1',
            name='sport',
            field=models.CharField(choices=[('basketball', 'Баскетбол'), ('football', 'Футбол'), ('tennis', 'Теннис'), ('swimming', 'Плавание'), ('volleyball', 'Волейбол'), ('taekwondo', 'Тхэквондо'), ('boxing', 'Бокс'), ('cycling', 'Велоспорт'), ('yoga', 'Йога')], max_length=20, verbose_name='Виды спорта'),
        ),
    ]
