# Generated by Django 5.1.1 on 2024-10-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0007_alter_payment1_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment1',
            name='sport',
            field=models.CharField(choices=[('basketball', 'Баскетбол'), ('football', 'Футбол'), ('tennis', 'Теннис'), ('swimming', 'Плавание'), ('volleyball', 'Волейбол'), ('taekwondo', 'Тхэквондо'), ('boxing', 'Бокс'), ('cycling', 'Велоспорт'), ('yoga', 'Йога')], max_length=100, verbose_name='Виды спорта'),
        ),
    ]
