# Generated by Django 5.1.1 on 2024-09-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_activation_code_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activation_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
