# Generated by Django 5.1.1 on 2024-09-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'Графики работы'},
        ),
        migrations.AddField(
            model_name='circleimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения'),
        ),
        migrations.AddField(
            model_name='hallimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=10, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Начало работы'),
        ),
        migrations.CreateModel(
            name='Schedul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('adults', 'Взрослые'), ('teens', 'Подростки'), ('kids', 'Дети')], max_length=10, verbose_name='Возрастная группа')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=10, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало занятий')),
                ('end_time', models.TimeField(verbose_name='Конец занятий')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='about_admin.circle', verbose_name='Кружок')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
