# Generated by Django 5.1.1 on 2024-09-24 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_admin', '0002_alter_schedule_options_circleimage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('sport', models.CharField(choices=[('basketball', 'Баскетбол'), ('football', 'Футбол'), ('volleyball', 'Волейбол'), ('tennis', 'Теннис'), ('boxing', 'Бокс'), ('cycling', 'Велоспорт'), ('taekwondo', 'Таэквондо'), ('swimming', 'Плавание'), ('yoga', 'Йога')], max_length=20, verbose_name='Спорт')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('sport', models.CharField(choices=[('basketball', 'Баскетбол'), ('football', 'Футбол'), ('volleyball', 'Волейбол'), ('tennis', 'Теннис'), ('boxing', 'Бокс'), ('cycling', 'Велоспорт'), ('taekwondo', 'Таэквондо'), ('swimming', 'Плавание'), ('yoga', 'Йога')], max_length=20, verbose_name='Спорт')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], max_length=10, verbose_name='Метод оплаты')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='about_admin.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
